INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('House', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Garden', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Babies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Internet', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('BedRoom', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('BathRoom', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Kitchen', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('LinvingRoom', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Storage', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Parking', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('School', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Office', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Laudry', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('BarRestaurante', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Aerport', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('garage', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Workstation', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Gas Station', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bus Station', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('House Keeping', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car Drive', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Airplane', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('BarRestaurante', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Aerport', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('garage', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Workstation', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Gas Station', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bus Station', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('House Keeping', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car Drive', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Airplane', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('BarRestaurante', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Aerport', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('garage', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Workstation', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Gas Station', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bus Station', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('House Keeping', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car Drive', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Airplane', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('BarRestaurante', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Aerport', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('garage', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Workstation', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Gas Station', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bus Station', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('House Keeping', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car Drive', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Airplane', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('BarRestaurante', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Airport', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('garage', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Workstation', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Gas Station', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bus Station', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('House Keeping', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car Drive', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Airplane', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('BarRestaurante', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Aerport', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('garage', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Workstation', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Gas Station', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bus Station', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('House Keeping', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car Drive', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Airplane', NOW());



